name: Python package

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest bs4 requests pandas selenium tqdm openpyxl
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: schedulebuild
        run: |
          python ee.py
      - name: commit files
        run: |
          git config --local user.email "1519166janssen@zuyd.nl"
          git config --local user.name "Roald1519166"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main

# on:
#   schedule:
#     - cron: "8 0 * * *" #runs at 08:00 UTC everyday
